### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by khanh-devos** [khanh-devos/capstone-ebike-reservation-backend#47]
- [Kanban board](https://github.com/khanh-devos/capstone-ebike-reservation-backend/projects/1)
- There are 5 members in our team:
1. me
2. [Rod.](https://github.com/rodrigopenayo98)
3. [Souad](https://github.com/souad988)
4. [Jacques](https://github.com/tchasinga)

![Screenshot_2023-11-02_09-50-01](https://github.com/khanh-devos/capstone-ebike-reservation-backend/assets/68627859/36c879c6-e473-4182-bedf-e3118f4964d3)

**Comment by Meltrust** [comment]
Hi @khanh-devos

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All cards have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] According to the project [requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md):

![image](https://github.com/khanh-devos/capstone-ebike-reservation-backend/assets/57421823/9a1db6a2-cfae-483d-886c-cd2928efb9f2)

At the time of this review, these are the pointings:

@tchasinga 15
@Log-benjamin 18
@rodrigopenayo98 21
@khanh-devos 26
@souad988 16

As you can see, the pointings do not meet the spec.  The maximum difference in points among each team member must not be greater than 5.

Kindly, make it so no team member has more than 5 points as compared to any other member of the team.



Tip:  Just reassign some tasks and/or play with the numbers, until the requirement is met.

Tip 2: You can count the points by clicking on any team member:

Example:

1. Click on a team member

![image](https://github.com/khanh-devos/capstone-ebike-reservation-backend/assets/57421823/9f4b16fe-55df-45cd-88dc-e9a03a1923d2)

2. Count the points

![image](https://github.com/khanh-devos/capstone-ebike-reservation-backend/assets/57421823/04cf3938-9a97-40cd-8d6e-e61efbda9790)

3. Repeat for every team member and be sure nobody has more than 5 points of difference.

That way, we will meet this particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md). 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @khanh-devos,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings are now equal according to spec✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
